# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "gelf"
  s.version = "1.4.0.beta1"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alexey Palazhchenko", "Lennart Koopmann"]
  s.date = "2012-01-17"
  s.description = "Library to send GELF messages to Graylog2 logging server. Supports plain-text, GELF messages and exceptions."
  s.email = "alexey.palazhchenko@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".gemtest",
    ".travis.yml",
    "CHANGELOG",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "benchmarks/incremental.rb",
    "benchmarks/notifier.rb",
    "gelf.gemspec",
    "lib/gelf.rb",
    "lib/gelf/logger.rb",
    "lib/gelf/notifier.rb",
    "lib/gelf/ruby_sender.rb",
    "lib/gelf/severity.rb",
    "test/helper.rb",
    "test/test_logger.rb",
    "test/test_notifier.rb",
    "test/test_ruby_sender.rb",
    "test/test_severity.rb"
  ]
  s.homepage = "http://github.com/Graylog2/gelf-rb"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "Library to send GELF messages to Graylog2 logging server."

  dev_dependencies = if RUBY_VERSION == '1.8.6'
    [
        [%q<shoulda>, ["~> 2.11.0"]],
        [%q<mocha>, ["~> 0.9.0"]]
    ]
  else
    [
        [%q<shoulda>, [">= 0"]],
        [%q<mocha>, [">= 0"]]
    ]
  end


  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<json>, [">= 0"])
      dev_dependencies.each do |dep|
        s.add_development_dependency(dep.first, dep.last)
      end
    else
      s.add_dependency(%q<json>, [">= 0"])
      dev_dependencies.each do |dep|
        s.add_dependency(dep.first, dep.last)
      end
    end
  else
    s.add_dependency(%q<json>, [">= 0"])
    dev_dependencies.each do |dep|
      s.add_dependency(dep.first, dep.last)
    end
  end
end

